
name: Hello Team

on: push

jobs:
  
  build:
    
    runs-on: ubuntu-latest

    
    steps:
      
      - uses: actions/checkout@v2
      
      - name: Hello Team
        with: ./.github/actions/hello-team